# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
        ('maestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Area')),
                ('cargo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_nacimiento', models.TimeField(blank=True, null=True)),
                ('registra_rips', models.BooleanField()),
                ('aseguradora', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Aseguradora')),
                ('grupo_sanguineo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.GrupoSanguineo')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('identificacion', models.CharField(max_length=255, null=True, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('telefono_oficina', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('ciudad_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_id', to='ubicacion.Ciudad')),
                ('ciudad_nacimiento_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_nacimiento_id', to='ubicacion.Ciudad')),
                ('estado_civil_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.EstadoCivil')),
                ('genero_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Genero')),
                ('ocupacion_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Ocupacion')),
                ('tipo_identificacion_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.TipoIdentificacion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Persona'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Rh'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_vinculacion_aseguradora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.TipoVinculacionAseguradora'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.EstadoEmpleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestras.Horario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Sede'),
        ),
    ]
