# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('rec_type', models.CharField(blank=True, max_length=20, null=True)),
                ('event_length', models.CharField(blank=True, max_length=20, null=True)),
                ('event_pid', models.CharField(blank=True, max_length=6, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadosAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados Agenda',
            },
        ),
        migrations.AddField(
            model_name='agenda',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.EstadosAgenda'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario_registra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usario_registra', to='users.Persona'),
        ),
    ]
